title: GitHub Pages Intro
author: Dave Finocchietti
email: david.hall.finocchietti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Just testing out GitHub Pages.

# social links
github_username:  Dave-Finocchietti

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
